name: Unit Test on CentOS

on:
  workflow_call:

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  BUNDLE_GEMFILE: test/Gemfile
  BASH_V: 5.1

permissions:
  contents: read

jobs:

  ########
  # DEBIAN
  ########
  run_test_debian:
      runs-on: ${{ matrix.os }}
      name: "OS: ${{ matrix.os }} - RUBY: ${{ matrix.ruby }}"
      strategy:
        fail-fast: false
        matrix:
          os: [centos-9]
          ruby: ['3.0','3.1','3.2','3.3']
      env:
        OS: ${{ matrix.os }}
        RUBY: ${{ matrix.ruby }}

      steps:

        - name: Checkout with all submodules
          uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
          with:
            fetch-depth: 3
            submodules: recursive

        - name: Get Ruby
          uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
          with:
            ruby-version: ${{ matrix.ruby }}
        - name: Install Gems
          run: |
            gem install bundler
            bundle install --jobs 4 --retry 3
          shell: bash

        - name: Run unit test script
          run: |
            chmod +x cloudflare-dns.sh
            chmod +x unit-test.sh
            bashcov -s ./unit-test.sh
          shell: bash

        - name: Upload reports to Codecov
          uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: OS_${{ matrix.os }}__Ruby_${{ matrix.ruby }}
            env_vars: OS,BASH_V,RUBY
            functionalities: gcov
            os: ${{ matrix.os }}
            name: "DynDNS Cloudflare - OS: ${{ matrix.os }} ; RUBY: ${{ matrix.ruby }}"
            verbose: true

        - name: Run codacy-coverage-reporter
          uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
          with:
            project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
            coverage-reports: coverage/coverage.xml
            language: Shell

