name: Unit Test on Ubuntu

on:
  workflow_call:
    inputs:
      OS:
        required: true
        type: string
      RUBY:
        required: true
        type: string
      CODECOV_TOKEN:
        required: true
        type: string
      CODACY_PROJECT_TOKEN:
        required: true
        type: string

permissions:
  contents: read

jobs:

  ########
  # UBUNTU
  ########
  run_test_ubuntu:
    runs-on: $OS
    name: "OS: $OS - RUBY: $RUBY"

    steps:

      - name: Get Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: $RUBY
      - name: Install Gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
        shell: bash

      - name: Run unit test script
        run: |
          chmod +x cloudflare-dns.sh
          chmod +x unit-test.sh
          bashcov -s ./unit-test.sh
        shell: bash

      - name: Upload reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: $CODECOV_TOKEN
          flags: OS_$OS__Ruby_$RUBY
          functionalities: gcov
          os: $OS
          name: "DynDNS Cloudflare - OS: $OS ; RUBY: $RUBY"
          verbose: true

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: $CODACY_PROJECT_TOKEN
          coverage-reports: coverage/coverage.xml
          language: Shell