name: Install Ruby and Gems

on:
  workflow_call:
    inputs:
      RUBY:
        required: true
        type: string
      BUNDLE_GEMFILE:
        required: true
        type: string

permissions:
    contents: read

jobs:

    get_ruby:
        name: "Get Ruby and Gems: ${{ inputs.RUBY }}"
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
            ruby-version: ${{ inputs.RUBY }}
            bundler-cache: true